version: '3.8'

services:
  frontend:
    build:
      context: .
    image: cw2serversidefrontend-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # Comment out restart for debugging
    # restart: unless-stopped
